version: "3.9"

services:
  server:
    image: "hoz73/server_python_docker"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - tp1


  client:
    image: "hoz73/client_python_docker"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - tp1

networks:
  tp1: