apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hoz73/server_python_docker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
#      - name: myclient
#        image: hoz73/client_python_docker
#        command: [ "sleep" ]
#        args: [ "infinity" ]
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#        ports:
#        - containerPort: 5050



---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 5000

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: myclient
#spec:
#  type: NodePort
#  selector:
#    app: myclient
#  ports:
#  - port: 90
#    targetPort: 8080
